/*==============================================================*/
/* DBMS name:      ORACLE Version 10g                           */
/* Created on:     29/06/2009 01:35:08 p.m.                     */
/*==============================================================*/


ALTER TABLE ACAE
   DROP CONSTRAINT FK_ACAE_ASSOCIATI_SUBSECTO;

ALTER TABLE ACAE
   DROP CONSTRAINT FK_ACAE_GENERALIZ_PERSONA;

ALTER TABLE CONTROLENVIO
   DROP CONSTRAINT FK_CONTROLE_ASSOCIATI_ACAE;

ALTER TABLE EXPEDIENTE
   DROP CONSTRAINT FK_EXPEDIEN_ASSOCIATI_ACAE;

ALTER TABLE ACAE
   DROP PRIMARY KEY CASCADE;

DROP TABLE TMP_ACAE CASCADE CONSTRAINTS;

RENAME ACAE TO TMP_ACAE;

/*==============================================================*/
/* Table: ACAE                                                  */
/*==============================================================*/
CREATE TABLE ACAE  (
   PERSONAID            INTEGER                         NOT NULL,
   TIPACAE              VARCHAR2(6),
   CLSSECTOR            VARCHAR2(6),
   TIPDOCUMENTOGER      VARCHAR2(6),
   CODDOCUMENTOGER      VARCHAR2(50),
   TXTAPELLIDOSNOMBRES  VARCHAR2(1000),
   TXTCARGO             VARCHAR2(255),
   TELEFONOGER          VARCHAR2(50),
   CONSTRAINT PK_ACAE PRIMARY KEY (PERSONAID)
);

COMMENT ON TABLE ACAE IS
'Autoridades sectoriales que expiden las certificaciones ambientales (con resolucion)';

INSERT INTO ACAE (PERSONAID, TIPACAE, CLSSECTOR, TIPDOCUMENTOGER, CODDOCUMENTOGER, TXTAPELLIDOSNOMBRES, TXTCARGO, TELEFONOGER)
SELECT PERSONAID, TIPACAE, CLSSECTOR, TIPDOCUMENTOGER, CODDOCUMENTOGER, TXTAPELLIDOSNOMBRES, TXTCARGO, TELEFONOGER
FROM TMP_ACAE;

ALTER TABLE ACAE
   ADD CONSTRAINT FK_ACAE_GENERALIZ_PERSONA FOREIGN KEY (PERSONAID)
      REFERENCES PERSONA (PERSONAID);

ALTER TABLE CONTROLENVIO
   ADD CONSTRAINT FK_CONTROLE_ASSOCIATI_ACAE FOREIGN KEY (PERSONAID)
      REFERENCES ACAE (PERSONAID);

ALTER TABLE EXPEDIENTE
   ADD CONSTRAINT FK_EXPEDIEN_ASSOCIATI_ACAE FOREIGN KEY (PERSONAID)
      REFERENCES ACAE (PERSONAID);

