prompt PL/SQL Developer import file
prompt Created on Martes, 05 de Mayo de 2009 by JORGE
set feedback off
set define off
prompt Disabling triggers for PARAMETROS...
alter table PARAMETROS disable all triggers;
prompt Deleting PARAMETROS...
delete from PARAMETROS;
prompt Loading PARAMETROS...
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (1, 'AGR', 'SEC', 'SECTORES', 'AGRICULTURA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (2, 'CET', 'SEC', 'SECTORES', 'COMERCIO EXTERIOR Y TURISMO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (3, 'DEF', 'SEC', 'SECTORES', 'DEFENSA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (4, 'EYM', 'SEC', 'SECTORES', 'ENERGÍA Y MINAS');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (5, 'PRO', 'SEC', 'SECTORES', 'PRODUCCIÓN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (6, 'MTC', 'SEC', 'SECTORES', 'TRANSPORTES Y COMUNICACIONES');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (7, 'SAL', 'SEC', 'SECTORES', 'SALUD');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (8, 'VCS', 'SEC', 'SECTORES', 'VIVIENDA CONSTRUCCIÓN Y SANEMIENTO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (9, 'INT', 'SEC', 'SECTORES', 'SECTOR INTERIOR');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (10, '001', 'SEC', 'SECTORES', 'AMAZONAS');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (11, '002', 'SEC', 'SECTORES', 'ANCASH');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (12, '003', 'SEC', 'SECTORES', 'APURIMAC');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (13, '004', 'SEC', 'SECTORES', 'AREQUIPA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (14, '005', 'SEC', 'SECTORES', 'AYACUCHO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (15, '006', 'SEC', 'SECTORES', 'CAJAMARCA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (16, '007', 'SEC', 'SECTORES', 'CALLAO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (17, '008', 'SEC', 'SECTORES', 'CUSCO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (18, '009', 'SEC', 'SECTORES', 'HUANCAVELICA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (19, '010', 'SEC', 'SECTORES', 'HUANUCO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (20, '011', 'SEC', 'SECTORES', 'ICA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (21, '012', 'SEC', 'SECTORES', 'JUNIN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (22, '013', 'SEC', 'SECTORES', 'LA LIBERTAD');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (23, '014', 'SEC', 'SECTORES', 'LAMBAYEQUE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (24, '015', 'SEC', 'SECTORES', 'LIMA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (25, '016', 'SEC', 'SECTORES', 'LORETO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (26, '017', 'SEC', 'SECTORES', 'MADRE DE DIOS');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (27, '018', 'SEC', 'SECTORES', 'MOQUEGUA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (28, '019', 'SEC', 'SECTORES', 'PASCO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (29, '020', 'SEC', 'SECTORES', 'PIURA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (30, '021', 'SEC', 'SECTORES', 'PUNO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (31, '022', 'SEC', 'SECTORES', 'SAN MARTIN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (32, '023', 'SEC', 'SECTORES', 'TACNA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (33, '024', 'SEC', 'SECTORES', 'TUMBES');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (34, '025', 'SEC', 'SECTORES', 'UCAYALI');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (35, 'CA1', 'IGA', 'INSTRUMENTO DE GESTION AMBIENTAL', 'DECLARACIÓN DE IMPACTO AMBIENTAL (DIA)');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (36, 'CA2', 'IGA', 'INSTRUMENTO DE GESTION AMBIENTAL', 'ESTUDIO DE IMPACTO AMBIENTAL SEMIDETALLADO (ESIA-SD)');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (37, 'CA3', 'IGA', 'INSTRUMENTO DE GESTION AMBIENTAL', 'ESTUDIO DE IMPACTO AMBIENTAL DETALLADO (ESIA-D)');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (38, 'CA0', 'IGA', 'INSTRUMENTO DE GESTION AMBIENTAL', 'PENDIENTE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (39, 'EVA', 'EST', 'ESTADO DEL TRÁMITE', 'EN EVALUACION');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (40, 'APR', 'EST', 'ESTADO DEL TRÁMITE', 'APROBADO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (41, 'NAP', 'EST', 'ESTADO DEL TRÁMITE', 'DESAPROBADO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (42, 'DES', 'EST', 'ESTADO DEL TRÁMITE', 'DESISTIDO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (43, 'ANU', 'EST', 'ESTADO DEL TRÁMITE', 'ANULADO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (44, 'LAB', 'DOP', 'ROL DOCUMENTO PERSONA', 'LABORATORIO QUE PARTICIPA EN LOS ANÁLISIS DEL EIA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (45, 'CON', 'DOP', 'ROL DOCUMENTO PERSONA', 'CONSULTOR QUE ELABORA EL EIA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (46, 'CAU', 'DOP', 'ROL DOCUMENTO PERSONA', 'CONSULTOR AUTORIZADO POR RESOLUCIÓN DE AUTORIZACIÓN CONSULTOR');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (47, 'AEX', 'DOP', 'ROL DOCUMENTO PERSONA', 'AUTORIDAD SECTORIAL QUE EMITE LA RESOLUCIÓN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (48, 'RES', 'DOC', 'TIPO DE DOCUMENTO', 'RESOLUCIÓN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (49, 'CAR', 'DOC', 'TIPO DE DOCUMENTO', 'CARTA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (50, 'EIA', 'DOC', 'TIPO DE DOCUMENTO', 'RESUMEN EJECUTIVO DEL IGA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (51, 'MEM', 'DOC', 'TIPO DE DOCUMENTO', 'MEMORANDUM');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (52, 'ITA', 'DOC', 'TIPO DE DOCUMENTO', 'INFORME TÉCNICO AMBIENTAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (53, 'DNI', 'TDI', 'TIPO DE DOCUMENTO IDENTIDAD', 'DOCUMENTO NACIONAL DE IDENTIDAD');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (54, 'RUC', 'TDI', 'TIPO DE DOCUMENTO IDENTIDAD', 'REGISTRO ÚNICO DE CONTRIBUYENTE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (55, 'CEX', 'TDI', 'TIPO DE DOCUMENTO IDENTIDAD', 'CARNÉ DE EXTRANJERÍA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (56, 'CON', 'PER', 'TIPO DE PERSONA', 'CONSULTOR AMBIENTAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (57, 'PRO', 'PER', 'TIPO DE PERSONA', 'PROPONENTE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (58, 'ACA', 'PER', 'TIPO DE PERSONA', 'ACAE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (59, 'LAB', 'PER', 'TIPO DE PERSONA', 'LABORATORIO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (60, 'RCA', 'RES', 'TIPO DE RESOLUCION', 'RESOLUCIÓN DE CERTIFICACIÓN AMBIENTAL APROBATORIA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (61, 'RCC', 'RES', 'TIPO DE RESOLUCION', 'RESOLUCIÓN DE CERTIFICACIÓN DE CONSULTORES');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (62, 'RCD', 'RES', 'TIPO DE RESOLUCION', 'RESOLUCIÓN DE CERTIFICACIÓN AMBIENTAL DESAPROBATORIA');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (63, 'SCA', 'TRA', 'TIPO DE TRAMITE', 'SOLICITUD DE CERTIFICACIÓN AMBIENTAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (64, 'SDE', 'TRA', 'TIPO DE TRAMITE', 'SOLICITUD DE DESISTIMIENTO DE TRÁMITE CERTIFICACIÓN AMBIENTAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (65, 'PSC', 'TRX', 'TIPO DE TRANSACCION', 'PRESENTACIÓN DE SOLICITUD DE CLASIFICACIÓN');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (66, 'DES', 'TRX', 'TIPO DE TRANSACCION', 'DESISTIMIENTO DE SOLICITUD');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (67, 'CLS', 'TRX', 'TIPO DE TRANSACCION', 'CLASIFICACIÓN DEL INSTRUMENTO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (68, 'PSI', 'TRX', 'TIPO DE TRANSACCION', 'PRESENTACIÓN DEL INSTRUMENTO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (69, 'EVA', 'TRX', 'TIPO DE TRANSACCION', 'EVALUACIÓN DEL INSTRUMENTO DE GESTIÓN AMBIENTAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (70, 'OBS', 'TRX', 'TIPO DE TRANSACCION', 'EMISION DE OPINIÓN TÉCNICA CON OBSERVACIONES');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (71, 'LOB', 'TRX', 'TIPO DE TRANSACCION', 'LEVANTAMIENTO DE OBSERVACIONES');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (72, 'ITA', 'TRX', 'TIPO DE TRANSACCION', 'CONCLUSIÓN DEL INFORME TÉCNICO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (73, 'RDE', 'TRX', 'TIPO DE TRANSACCION', 'RESOLUCION DE DESAPROBACIÓN DE LA SOLICITUD DE CERTIFICACION');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (74, 'OBS', 'EST', 'ESTADO DEL TRÁMITE', 'OBSERVADO');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (75, 'RAP', 'TRX', 'TIPO DE TRANSACCION', 'RESOLUCION DE APROBACIÓN DE LA SOLICITUD DE CERTIFICACION');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (76, 'GLO', 'TSS', 'TIPO DE SUBSECTOR', 'GOBIERNO LOCAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (77, 'SSE', 'TSS', 'TIPO DE SUBSECTOR', 'SUBSECTOR MINISTERIAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (78, 'DRE', 'TSS', 'TIPO DE SUBSECTOR', 'DIRECCION MINISTERIAL');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (79, 'ACA', 'TUS', 'TIPO DE USUARIO', 'USUARIO DE ACAE');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (80, 'ADM', 'TUS', 'TIPO DE USUARIO', 'USUARIO ADMINISTRADOR');
insert into PARAMETROS (IDPARAMETRO, CODPARAMETRO, TIPPARAMETRO, TXTPARAMETRO, TXTVALOR)
values (81, 'DIR', 'DIR', 'DIRECTORIO DE IMAGENES', 'E:\DATOS\IMAGENES\');
prompt 81 records loaded
prompt Enabling triggers for PARAMETROS...
alter table PARAMETROS enable all triggers;
set feedback on
set define on
prompt Done.
